export const surpriseMePrompts = [
  "A sprawling ancient jungle temple reclaimed by nature, with massive roots snaking through crumbling stone corridors.",
  "A futuristic floating observatory hovering above Saturn’s rings, with scientists peering through massive crystal lenses.",
  "A cozy mountain inn built into a snowy cliffside, its warm lanterns glowing through heavy snowfall.",
  "A neon-lit underwater highway where aquatic vehicles glide past luminous sea creatures.",
  "A magical bakery run by elves, where pastries float, sparkle, and rearrange themselves on enchanted shelves.",
  "A vast desert with floating monoliths casting impossible shadows over sand dunes.",
  "A hidden village built entirely inside towering bamboo stalks, connected by delicate rope bridges.",
  "A celestial train made of stardust traveling across constellations in the night sky.",
  "A serene monastery perched atop a pillar of rock, with monks meditating above swirling clouds.",
  "A retro robot repair shop filled with spare parts, quirky automata, and flickering holographic manuals.",
  "A grand hall inside a dragon’s lair, where treasure piles illuminate ancient murals on the walls.",
  "A futuristic orchard where fruit grows on bioluminescent floating vines nurtured by drones.",
  "A sanctuary in the sky where giant koi fish swim through clouds like water.",
  "A colossal subterranean city powered by glowing crystals embedded in cavern ceilings.",
  "A timeless library ship sailing through an endless cosmic ocean.",
  "A whimsical toy factory where every machine is powered by steam and magic.",
  "A snowy owl-themed palace rising out of a frozen lake, shimmering like carved ice.",
  "A surreal canyon shaped like enormous fossilized creatures, dotted with glowing minerals.",
  "A twilight meadow where spirits and ethereal animals roam among floating lotus lanterns.",
  "A kingdom built on the backs of giant wandering turtles that travel across oceans.",
  "A bioluminescent swamp where trees glow in swirling patterns and will-o’-wisps dance across the water.",
  "A neon festival in a futuristic desert city, with holographic performers and energy-powered kites.",
  "A cozy witch’s cottage stacked haphazardly with enchanted trinkets, potions, and floating brooms.",
  "A celestial forge where blacksmiths craft weapons from falling stars.",
  "A mythical floating coliseum where warriors battle using elemental magic.",
  "A bustling marketplace inside a volcanic cavern illuminated by molten lava rivers.",
  "A sky kingdom where colossal birds serve as transportation across floating mountains.",
  "A robotic wildlife reserve where mechanical animals roam freely, mimicking their organic counterparts.",
  "A super-modern eco-city covered in vertical forests and sky farms, thriving above the clouds.",
  "A cyber-samurai dojo glowing with neon edges and holographic training dummies.",
  "A secret ocean trench city inhabited by deep-sea adventurers and phosphorescent creatures.",
  "A timeless, foggy harbor where ghost ships drift through the mist under dim lantern light.",
  "A snowy enchanted forest where trees hum with magic and aurora lights trail through branches.",
  "A dimensional rift opening in a quaint village, revealing an alternate version of the same place.",
  "A giant crystal tree at the heart of a magical realm, with homes embedded in its glowing branches.",
  "A robotic garden where metallic plants bloom into shifting geometric flowers.",
  "A pirate haven carved into massive sea cliffs with wooden walkways and glowing treasure caves.",
  "A mystical tea house floating on a cloud island, serving beverages infused with stardust.",
  "A colossal hourglass-shaped tower where each level represents a different historical era.",
  "A desert metropolis powered entirely by giant solar towers shaped like ancient obelisks.",
  "A dreamlike city where rivers flow upward into the sky, forming floating waterfalls.",
  "A magical train station that appears only during full moons, its platform glowing ethereally.",
  "A forgotten fortress hidden in a blizzard, guarded by armored snow spirits.",
  "A futuristic metropolis built around a massive AI core that glows like a suspended sun.",
  "A floating botanical conservatory filled with exotic interdimensional flora.",
  "A haunted amusement park where ghostly rides operate on their own under a moonlit sky.",
  "A pristine coral palace ruled by merfolk, decorated with seashell spires and glowing pearls.",
  "A colossal tree stump turned into a sprawling village with spiral stairways and lantern-lit homes.",
  "A vast crystal desert where dunes shimmer like glass and mysterious figures wander the horizon.",
  "A cosmic library suspended in outer space with books that project living scenes when opened."
];
