// 50 prompts
export const surpriseMePrompts = [
  "A serene countryside cottage engulfed in the vibrant hues of a sunset, with a cozy fireplace glowing through the window.",
  "An old, overgrown Victorian mansion covered in ivy, standing tall amidst a dense misty forest.",
  "An urban rooftop garden atop a skyscraper, featuring lush greenery, comfortable seating, and breathtaking city views.",
  "A bustling street market in a futuristic city, where holographic displays and traditional stalls blend seamlessly.",
  "A charming bookstore nestled on a cobblestone street, its shelves adorned with ancient manuscripts and rare books.",
  "An underwater research station surrounded by vibrant coral reefs, with transparent walls offering views of marine life.",
  "A steampunk-style airship soaring through the clouds, its ornate gears and propellers propelling it forward.",
  "An enchanted library hidden within a magical realm, illuminated by floating orbs and guarded by mythical creatures.",
  "A secluded cabin at the edge of a tranquil lake, with a wooden dock extending over clear water and reflecting stars.",
  "A retro-futuristic cityscape inspired by the 1950s, where classic cars share the road with levitating vehicles.",
  "A hidden cave illuminated by bioluminescent fungi, revealing intricate rock formations and a subterranean waterfall.",
  "An ancient temple carved into the side of a mountain, overlooking a vast valley painted with autumnal colors.",
  "A cyberpunk alleyway adorned with holographic graffiti, neon signs, and bustling futuristic market stalls.",
  "A coastal town with pastel-colored houses, where a lighthouse stands tall against a backdrop of crashing waves.",
  "A high-tech laboratory with intricate machinery, where scientists work alongside AI assistants to conduct experiments.",
  "A floating island city suspended among the clouds, accessible via intricate bridges and cable cars.",
  "A medieval castle perched atop a rocky cliff, surrounded by a swirling river and lush forests.",
  "An arctic research station amidst a frozen tundra, with scientists studying the aurora borealis from transparent domes.",
  "A secret garden hidden behind an ancient stone archway, filled with exotic plants and enchanted creatures.",
  "A vibrant city park in spring, where cherry blossom trees cast a delicate pink canopy over meandering pathways.",
  "A clockwork city where gears and cogwheels power everything, from transportation to streetlights.",
  "An art deco-inspired metropolis with towering skyscrapers adorned with intricate patterns and golden accents.",
  "A tranquil zen garden with meticulously raked sand, bonsai trees, and a peaceful koi pond.",
  "An ancient forest at twilight, where fireflies illuminate the pathways leading to hidden groves.",
  "A vibrant floating market on a series of interconnected boats, selling exotic fruits, spices, and trinkets.",
  "An otherworldly canyon with massive crystal formations that emit a soft, ethereal glow.",
  "A quaint village in a valley surrounded by majestic waterfalls and lush, terraced farmland.",
  "An abandoned space station orbiting a distant planet, its interiors frozen in time.",
  "A high-speed magnetic train racing through a hypermodern urban landscape.",
  "A mystical library where books come to life, their characters interacting with readers.",
  "A mountain range with peaks capped in snow, where ancient ruins are buried beneath ice and time.",
  "A mystical desert oasis with an emerald-green pool surrounded by palm trees and hidden treasures.",
  "A city built within the roots of an ancient tree, its branches forming bridges between districts.",
  "A futuristic underwater city with transparent domes, showcasing marine life and coral gardens.",
  "A lush rainforest canopy walkway, revealing breathtaking views of colorful birds and exotic flora.",
  "A colossal mechanical creature resembling an elephant, roaming a post-apocalyptic wasteland.",
  "A cosmic observatory on a distant moon, where astronomers study nebulae and distant galaxies.",
  "A fantastical carnival where mythical creatures take on roles as performers and attractions.",
  "A realm of floating islands held aloft by enchanted balloons, accessible only by airships.",
  "A hidden alchemist's laboratory filled with bubbling potions and intricate magical apparatuses.",
  "A cybernetic jungle with bioluminescent animals and towering neon plants.",
  "A Victorian-era city with airships dotting the sky and gas lamp-lit streets.",
  "A terraformed Mars colony with domed cities, terra-cotta landscapes, and Elon Musk as mayor.",
  "A coastal village in a bioluminescent bay, where the sea glows with a surreal radiance.",
  "A forgotten underwater city where ancient merfolk civilizations once thrived.",
  "A cascading waterfall that leads into an underground cave system filled with glowing crystals.",
  "A celestial city on the moon, with shimmering towers and space-faring vessels docking in orbit.",
  "A mythic forest where trees sprout colorful lanterns that light up the night.",
  "An alternate reality where animals have evolved to have human-like traits and civilizations.",
  "A gravity-defying cityscape where buildings seemingly float in mid-air, connected by staircases and platforms."
];